# Copyright 2021 Canonical Ltd.
# See LICENSE file for licensing details.

options:
  admin-port:
    type: string
    default: '9901'
    description: Admin port
  http-port:
    type: string
    default: '9090'
    description: Proxied HTTP port
  metrics-api:
    type: string
    default: '/stats/prometheus'
    description: metrics api route
  metrics-scrape-interval:
    type: string
    default: '30s'
    description: how often metrics are scraped
